name: pr

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-15

    env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 100 # a random number to avoid danger failure. Ref: https://github.com/danger/danger/issues/768#issuecomment-398893158

    - uses: jdx/mise-action@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: Check PR title
      run: |
        bundle exec danger --dangerfile=Dangerfiles/check-pr-info.rb \
                           --danger_id=check-pr-info \
                           --remove-previous-comments
    - name: Run Swiftlint
      run: |
        bundle exec danger --dangerfile=Dangerfiles/run-swiftlint.rb \
                            --danger_id=run-swiftlint \
                            --remove-previous-comments
